from setuptools import setup, find_packages
from pybind11.setup_helpers import Pybind11Extension, build_ext

setup(
    name="open-deep-tda",
    version="0.3.0",
    description="Topology-regularized parametric dimensionality reduction",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    license="MIT",
    license_files=["LICENSE", "THIRD_PARTY_NOTICES.md"],
    author="Open Deep-TDA contributors",
    url="https://github.com/roshameow/open-deep-tda",
    project_urls={"Source": "https://github.com/roshameow/open-deep-tda",
                  "Issues": "https://github.com/roshameow/open-deep-tda/issues",
                  "Documentation": "https://github.com/roshameow/open-deep-tda#readme"},
    classifiers=["Development Status :: 3 - Alpha", "Programming Language :: Python :: 3",
                 "Programming Language :: C++", "Operating System :: POSIX",
                 "Topic :: Scientific/Engineering :: Artificial Intelligence"],
    python_requires=">=3.9",
    package_dir={"": "python"},
    packages=find_packages("python"),
    ext_modules=[Pybind11Extension(
        "open_deep_tda._core", ["src/persistence.cpp", "bindings/module.cpp"],
        include_dirs=["include"], cxx_std=17,
    )],
    cmdclass={"build_ext": build_ext},
    install_requires=["numpy>=1.21", "scipy>=1.8", "torch>=2.6", "scikit-learn>=1.0"],
    extras_require={"dev": ["pytest>=7", "ripser>=0.6", "pybind11>=2.12", "Pillow>=9.1", "psutil>=5.9"],
                    "plot": ["matplotlib>=3.5"], "benchmark": ["umap-learn>=0.5", "threadpoolctl>=3.1"],
                    "ann": ["pynndescent>=0.5.13"],
                    "images": ["Pillow>=9.1", "ripser>=0.6", "pynndescent>=0.5.13", "psutil>=5.9"]},
    entry_points={"console_scripts": ["deep-tda=open_deep_tda.cli:main"]},
    zip_safe=False,
)
